---
- hosts: production
  vars:
    - dist: ubuntu18.04
    - vg: r10
    - guest_name: phd-test-http
    - vcpus: 4
    - memory: 8192
    - disk_size: 20G
    - bridge: br0
    - mac: 52:54:00:68:ec:bc
  roles:
    - { role: vm-create, tags: vm-create }
