- name: set vm vars for ({{ dist }})
  include_vars: "{{ dist }}/vm.yml"

- name: set preseed vars for ({{ dist }})
  include_vars: "{{ dist }}/preseed.yml"

- name: display all environment variables
  debug:
    var: environment
    verbosity: 4

### Debian
- name: start debian installation
  include: install-vm-debian.yml
  when: template_type == 'debian'

### Ubuntu
- name: start ubuntu installation
  include: install-vm-debian.yml
  when: template_type == 'ubuntu'

