---
- name: check if '{{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}' exists
  stat:
    path: '{{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}'
    get_checksum: no
  register: virtual_disk_root_stat

- name: check if '/etc/libvirt/qemu/{{ virtual_guest_name }}.xml' exists
  stat:
    path: '/etc/libvirt/qemu/{{ virtual_guest_name }}.xml'
    get_checksum: no
  register: virtual_guest_xml_stat

- name: create virtual base path
  file:
    path: '{{ virtual_base_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: include create disks
  include_tasks: create-disks.yml
  when: not (virtual_disk_root_stat.stat.exists is defined and virtual_disk_root_stat.stat.exists == True)

- name: include define guest
  include_tasks: define-guest.yml
  when: not (virtual_guest_xml_stat.stat.exists is defined and virtual_guest_xml_stat.stat.exists == True)
