---
- name: create template
  command: '{{ virtual_template_command }}'
  args:
    creates: '{{ virtual_template_base }}-*'
  when: virtual_template_create

- name: "clone disks ({{ ', '.join(virtual_disks_main) }}) from template"
  command: 'dd if={{ virtual_template_base }}-{{ item }} of={{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-{{ item }} bs=1M'
  loop: '{{ virtual_disks_main }}'
