---
- stat:
    path: "{{ virtual_disk_prefix }}{{ (item.1.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount|default('{{ virtual_disk_prefix }}sd' + virtual_disks_letters[item.0])|replace('/', '-') }}"
  register: virtual_disks_stat
  with_indexed_items: '{{ virtual_disks }}'

- fail:
    msg: 'guest disk already exists: {{ item.invocation.module_args.path }}'
  when: item.stat.exists is defined and item.stat.exists == True
  with_items: '{{ virtual_disks_stat.results }}'

- name: create extra disks lvs
  lvol:
    vg: '{{ (item.1.vg|default(virtual_disk_vg)) }}'
    lv: "{{ virtual_guest_name }}{{ item.1.mount|default(virtual_disk_prefix + 'sd' + virtual_disks_letters[item.0])|replace('/', '-') }}"
    size: "{{ item.1.size }}"
  with_indexed_items: '{{ virtual_disks }}'

- name: include fill extra disks
  include_tasks: fill-extra-disks.yml
  when: virtual_bootstrap_method == 'clone' or virtual_bootstrap_method == 'bootstrap'
