---
- name: "create main disks ({{ ', '.join(virtual_disks_main) }}) lv(s)"
  lvol:
    vg: '{{ virtual_disk_vg }}'
    lv: '{{ virtual_guest_name }}-{{ item }}'
    size: '{{ virtual_disks_main_size[item] }}'
  loop: '{{ virtual_disks_main }}'
  when: virtual_bootstrap_method != 'bootstrap'

- name: include clone disks
  include_tasks: clone-disks.yml
  when: virtual_bootstrap_method == 'clone'

- name: include extra disks
  include_tasks: create-extra-disks.yml
  when: virtual_disks

- block:

  - name: umount root filesystem
    command: 'umount /dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root'

  - name: remove mount dir
    file:
      path: '{{ virtual_mount_path }}'
      state: absent

  when: virtual_bootstrap_method == 'clone'

- name: include host boot
  include_tasks: host-boot.yml
  when: virtual_boot_method == 'host'
