---
- name: create extra disks lvs
  lvol:
    vg: '{{ (item.1.vg | default(virtual_disk_vg)) }}'
    lv: "{{ virtual_guest_name }}{{ item.1.mount | default((item.prefix | default(virtual_disk_prefix)) + '/' + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0]) | replace('/', '-') }}"
    size: "{{ item.1.size }}"
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'lv'

- name: "create extra disks zvols"
  zfs:
    name: "{{ (item.1.vg | default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount | default((item.prefix | default(virtual_disk_prefix)) + '/' + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0]) | replace('/', '-') }}"
    state: present
    extra_zfs_properties: '{{ item.1.zfs_props | default({}) | combine(virtual_disk_zfs_props) | combine({"volsize": item.1.size}) | combine({"volblocksize": item.1.bs | default(virtual_disk_bs)}) }}'
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'zvol'

- name: "create extra disks files (fallocate)"
  command: "fallocate -l {{ item.1.size }} {{ (item.prefix | default(virtual_disk_prefix)) }}{{ (item.1.vg | default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount | default((item.prefix | default(virtual_disk_prefix)) + '/' + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0]) | replace('/', '-') }}{{ (item.suffix | default(virtual_disk_suffix)) }}"
  with_indexed_items: "{{ (virtual_disks | selectattr('import', 'undefined') | list) + (virtual_disks | selectattr('import', 'defined') | rejectattr('import') | list) }}"
  when: virtual_disk_type == 'file' and virtual_disk_file_allocation == 'fallocate'

- name: "create extra disks files (qemu-img)"
  command:
    cmd: "qemu-img create -f raw -o preallocation=full {{ (item.prefix | default(virtual_disk_prefix)) }}{{ (item.1.vg | default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount | default((item.prefix | default(virtual_disk_prefix)) + '/' + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0]) | replace('/', '-') }} {{ item.1.size }}{{ (item.suffix | default(virtual_disk_suffix)) }}"
  throttle: 1
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'file' and virtual_disk_file_allocation == 'qemu-img'

- name: include fill extra disks
  include_tasks: fill-extra-disks.yml
  when: virtual_bootstrap_method == 'clone' or virtual_bootstrap_method == 'bootstrap'
