---
- stat:
    path: "{{ virtual_disk_prefix }}{{ (item.1.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount|default('{{ virtual_disk_prefix }}{{ virtual_disk_bus_id }}d' + virtual_disks_letters[item.0])|replace('/', '-') }}"
  register: virtual_disks_stat
  with_indexed_items: '{{ virtual_disks }}'

- fail:
    msg: 'guest disk already exists: {{ item.invocation.module_args.path }}'
  when: item.stat.exists is defined and item.stat.exists == True
  with_items: '{{ virtual_disks_stat.results }}'

- name: create extra disks lvs
  lvol:
    vg: '{{ (item.1.vg|default(virtual_disk_vg)) }}'
    lv: "{{ virtual_guest_name }}{{ item.1.mount|default(virtual_disk_prefix + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0])|replace('/', '-') }}"
    size: "{{ item.1.size }}"
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'lv'

- name: "create extra disks zvols"
  zfs:
    name: "{{ (item.1.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount|default(virtual_disk_prefix + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0])|replace('/', '-') }}"
    state: present
    extra_zfs_properties:
      volsize: "{{ item.1.size }}"
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'zvol'

- name: "create extra disks files (fallocate)"
  command: "fallocate -l {{ item.1.size }} {{ virtual_disk_prefix }}{{ (item.1.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount|default(virtual_disk_prefix + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0])|replace('/', '-') }}"
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'file' and virtual_disk_file_allocation == 'fallocate'

- name: "create extra disks files (qemu-img)"
  command: "qemu-img create -f raw -o preallocation=full {{ virtual_disk_prefix }}{{ (item.1.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ item.1.mount|default(virtual_disk_prefix + virtual_disk_bus_id + 'd' + virtual_disks_letters[item.0])|replace('/', '-') }} {{ item.1.size }}"
  throttle: 1
  with_indexed_items: '{{ virtual_disks }}'
  when: virtual_disk_type == 'file' and virtual_disk_file_allocation == 'qemu-img'

- name: include fill extra disks
  include_tasks: fill-extra-disks.yml
  when: virtual_bootstrap_method == 'clone' or virtual_bootstrap_method == 'bootstrap'
