---
- name: define guest
  command: |
    virt-install \
    --name={{ virtual_guest_name }} \
    --virt-type=kvm \
    {% if virtual_memory_hotpluggable %}
    --cpu=model={{ virtual_cpu }},cell0.id=0,cell0.cpus={{ virtual_numa_cell_cpus }},cell0.memory={{ virtual_numa_cell_memory }} \
    --memory=memory={{ virtual_memory }},hotplugmemorymax={{ virtual_memory_max }},hotplugmemoryslots={{ virtual_memory_slots }} \
    {% else %}
    --cpu={{ virtual_cpu }} \
    --memory={{ virtual_memory }} \
    {% endif %}
    --cputune={{ virtual_cputune }} \
    {% if virtual_cpus_hotpluggable %}
    --vcpus=vcpus={{ virtual_cpus }},maxvcpus={{ virtual_cpus_max }} \
    {% else %}
    --vcpus={{ virtual_cpus }} \
    {% endif %}
    {% if virtual_memory_hugepages %}
    --memorybacking=hugepages=yes,size={{ virtual_memory_hugepages_size }},unit={{ virtual_memory_hugepages_unit }} \
    {% endif %}
    {% if virtual_memory_balloon %}
    --memballoon=virtio \
    {% else %}
    --memballoon=none \
    {% endif %}
    --controller=type=scsi,model=virtio-scsi \
    {% if virtual_boot_method == 'part' %}
    --disk=path=/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-boot,bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target=0,address.unit=0,boot_order=1 \
    {% endif %}
    --disk=path=/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root,bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target={{ virtual_disk_boot_index }},address.unit={{ virtual_disk_boot_index }}{{ '' if virtual_boot_method == 'part' else ',boot_order=1' }} \
    {% for disk in virtual_disks|default([]) %}
    --disk=path=/dev/{{ (disk.vg|default(virtual_disk_vg)) }}/{{ virtual_guest_name }}{{ disk.mount|default('/dev/sd' + virtual_disks_letters[loop.index - 1])|replace('/', '-') }},bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target={{ loop.index + virtual_disk_boot_index|int }},address.unit={{ loop.index + virtual_disk_boot_index|int }} \
    {% endfor %}
    {% if virtual_bootstrap_method != 'install' %}
    --import \
    {% else %}
    --location={{ virtual_location }} \
    --extra-args='{{ virtual_install_kernel_args }}' \
    {% endif %}
    {% if virtual_boot_method == 'preseed' %}
    --initrd-inject={{ virtual_preseed_path }}
    {% endif %}
    --os-type=linux \
    --os-variant={{ virtual_os_variant }} \
    --console=pty,target_type=serial \
    {% if virtual_boot_method == 'host' %}
    --boot=kernel={{ virtual_kernel_base_path }}/{{ virtual_guest_name }}/vmlinuz,initrd={{ virtual_kernel_base_path }}/{{ virtual_guest_name }}/initrd.img,kernel_args="{{ virtual_kernel_args }}" \
    {% endif %}
    {% if virtual_mac is defined %}
    --network=bridge={{ virtual_bridge }},model=virtio,target={{ virtual_interface_name }},mac={{ virtual_mac }} \
    {% else %}
    --network=bridge={{ virtual_bridge }},model=virtio,target={{ virtual_interface_name }} \
    {% endif %}
    --nographics \
    --noautoconsole \
    --autostart
