---
- name: set fact virtual_mount_path
  set_fact:
    virtual_mount_path: "{{ virtual_mount_base_path }}/{{ virtual_guest_name }}_{{ 1000000 | random | hash('sha1') }}"

- name: check root filesystem
  command: 'e2fsck -pf {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}'

- name: change root filesystem uuid
  shell: 'echo y | tune2fs {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }} -U random'

- name: resize root filesystem
  command: 'resize2fs {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}'

- name: create root mount dir
  file:
    path: '{{ virtual_mount_path }}/root'
    state: directory

- name: mount root filesystem
  command: 'mount {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }} {{ virtual_mount_path }}/root'
  args:
    warn: false

- name: check if we have syslinux
  stat:
    path: '{{ virtual_mount_path }}/root/syslinux.cfg'
  register: virtual_guest_syslinux_stat

- name: modify syslinux bus id
  replace:
    path: '{{ virtual_mount_path }}/root/syslinux.cfg'
    regexp: '/dev/sd'
    replace: '/dev/{{ virtual_disk_bus_id }}d'
  when: virtual_disk_bus_id != 's' and virtual_guest_syslinux_stat.stat.exists

- name: modify fstab bus id
  replace:
    path: '{{ virtual_mount_path }}/root/etc/fstab'
    regexp: '/dev/sd'
    replace: '/dev/{{ virtual_disk_bus_id }}d'
  when: virtual_disk_bus_id != 's'

- name: set hostname
  shell: 'echo "{{ virtual_guest_name }}" > {{ virtual_mount_path }}/root/etc/hostname'

- include_tasks: copy_host_keys.yml
  loop: '{{ virtual_ssh_host_key_types }}'
  loop_control:
    loop_var: ssh_host_key_type
  when: virtual_ssh_host_key_types and virtual_ssh_host_keys_public and virtual_ssh_host_keys_private

- name: set root password hash
  lineinfile:
    path: '{{ virtual_mount_path }}/root/etc/shadow'
    regexp: '^root:([^:])*(.*)$'
    line: 'root:{{ virtual_root_password_hash }}\2'
    backrefs: yes
  no_log: true
  when: virtual_root_password_hash != ''
