---
- name: set fact virtual_mount_path
  set_fact:
    virtual_mount_path: "{{ virtual_mount_base_path }}/{{ virtual_guest_name }}_{{ 1000000 | random | hash('sha1') }}"

- name: check root filesystem
  # noqa no-changed-when
  command: 'e2fsck -pf {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}'

- name: change root filesystem uuid
  # noqa no-changed-when
  shell: 'echo y | tune2fs {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }} -U random'

- name: resize root filesystem
  # noqa no-changed-when
  command: 'resize2fs {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }}'

- name: create root mount dir
  file:
    path: '{{ virtual_mount_path }}/root'
    state: directory  # noqa risky-file-permissions

- name: mount root filesystem
  # noqa no-changed-when
  command: 'mount {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }} {{ virtual_mount_path }}/root'

- name: check if we have syslinux
  stat:
    path: '{{ virtual_mount_path }}/root/syslinux.cfg'
  register: virtual_guest_syslinux_stat

- name: when not virtual disk by uuid
  when: not virtual_disk_by_uuid
  block:

  - name: modify syslinux bus id
    replace:
      path: '{{ virtual_mount_path }}/root/syslinux.cfg'
      regexp: '/dev/sd'
      replace: '/dev/{{ virtual_disk_bus_id }}d'
    when: virtual_disk_bus_id != 's' and virtual_guest_syslinux_stat.stat.exists

  - name: modify fstab bus id
    replace:
      path: '{{ virtual_mount_path }}/root/etc/fstab'
      regexp: '/dev/sd'
      replace: '/dev/{{ virtual_disk_bus_id }}d'
    when: virtual_disk_bus_id != 's'

- name: when virtual disk by uuid
  when: virtual_disk_by_uuid
  block:

  - name: modify syslinux root uuid
    shell: 'sed -i "s/\/dev\/sda/UUID=$(blkid -s UUID -o value {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }})/" {{ virtual_mount_path }}/root/syslinux.cfg'
    when: virtual_guest_syslinux_stat.stat.exists

  - name: when virtual boot method is not part
    when: virtual_boot_method != 'part'
    block:

    - name: modify fstab root uuid
      # noqa no-changed-when
      shell: 'sed -i "s/\/dev\/sda/UUID=$(blkid -s UUID -o value {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }})/" {{ virtual_mount_path }}/root/etc/fstab'

  - name: when virtual boot method is part
    when: virtual_boot_method == 'part'
    block:

    - name: modify fstab root uuid
      # noqa no-changed-when
      shell: 'sed -i "s/\/dev\/sdb/UUID=$(blkid -s UUID -o value {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root{{ virtual_disk_suffix }})/" {{ virtual_mount_path }}/root/etc/fstab'

    - name: modify fstab root uuid
      # noqa no-changed-when
      shell: 'sed -i "s/\/dev\/sda1/UUID=$(blkid -s UUID -o value {{ virtual_disk_prefix }}{{ virtual_disk_vg }}/{{ virtual_guest_name }}-boot{{ virtual_disk_suffix }})/" {{ virtual_mount_path }}/root/etc/fstab'

- name: set hostname
  # noqa no-changed-when
  shell: 'echo "{{ virtual_guest_name }}" > {{ virtual_mount_path }}/root/etc/hostname'

- name: include tasks from copy_host_keys.yml
  include_tasks: copy_host_keys.yml
  loop: '{{ virtual_ssh_host_key_types }}'
  loop_control:
    loop_var: ssh_host_key_type
  when: virtual_ssh_host_key_types and virtual_ssh_host_keys_public and virtual_ssh_host_keys_private

- name: set root password hash
  lineinfile:
    path: '{{ virtual_mount_path }}/root/etc/shadow'
    regexp: '^root:([^:])*(.*)$'
    line: 'root:{{ virtual_root_password_hash }}\2'
    backrefs: yes
  no_log: true
  when: virtual_root_password_hash != ''
