---
- name: set vm vars for ({{ dist }})
  include_vars: "{{ dist }}/vm.yml"

- stat:
    path: '/dev/{{ vg }}/{{ guest_name }}-root'
  register: guest_lvm_root

- fail:
    msg: 'guest root lvm already exists!'
  when: guest_lvm_root.stat.exists is defined and guest_lvm_root.stat.exists == True

- stat:
    path: '/dev/{{ vg }}/{{ guest_name }}-boot'
  register: guest_lvm_boot

- fail:
    msg: 'guest boot lvm already exists!'
  when: guest_lvm_boot.stat.exists is defined and guest_lvm_boot.stat.exists == True

- stat:
    path: '/etc/libvirt/qemu/{{ guest_name }}.xml'
  register: guest_xml

- fail:
    msg: 'guest xml already exists!'
  when: guest_xml.stat.exists is defined and guest_xml.stat.exists == True

- name: create boot lv
  lvol:
    vg: '{{ vg }}'
    lv: '{{ guest_name }}-boot'
    size: '512M'

- name: create root lv
  lvol:
    vg: '{{ vg }}'
    lv: '{{ guest_name }}-root'
    size: "{{ disk_size|default('2G') }}"

- name: dump boot disk from template
  command: 'dd if=/dev/r10/vm-template-boot of=/dev/{{ vg }}/{{ guest_name }}-boot bs=1M'

- name: dump root filesystem from template
  command: 'dd if=/dev/r10/vm-template-root of=/dev/{{ vg }}/{{ guest_name }}-root bs=1M'

- name: check root filesystem
  command: 'e2fsck -pf /dev/{{ vg }}/{{ guest_name }}-root'

- name: change root filesystem uuid
  shell: 'echo y | tune2fs /dev/{{ vg }}/{{ guest_name }}-root -U random'

- name: resize root filesystem
  command: 'resize2fs /dev/{{ vg }}/{{ guest_name }}-root'

- name: mount root filesystem
  command: 'mount /dev/{{ vg }}/{{ guest_name }}-root /mnt'
  args:
    warn: false

- name: set hostname
  shell: 'echo "{{ guest_name }}" > /mnt/etc/hostname'

- name: umount root filesystem
  command: 'umount /dev/{{ vg }}/{{ guest_name }}-root'

- name: create vm
  command: |
    virt-install \
    --virt-type=kvm \
    --cpu=host \
    --name={{ guest_name }} \
    --vcpus={{ vcpus }} \
    --memory={{ memory }} \
    --memorybacking=hugepages=yes \
    --controller=type=scsi,model=virtio-scsi \
    --disk=path=/dev/{{ vg }}/{{ guest_name }}-boot,bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target=0,address.unit=0,boot_order=1 \
    --disk=path=/dev/{{ vg }}/{{ guest_name }}-root,bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target=1,address.unit=1 \
    --import \
    --os-type=linux \
    --os-variant={{ os_variant }} \
    --console=pty,target_type=serial \
    {% if mac is defined %}
    --network=bridge={{ bridge }},model=virtio,mac={{ mac }} \
    {% else %}
    --network=bridge={{ bridge }},model=virtio \
    {% endif %}
    --nographics \
    --noautoconsole \
    --autostart
