- name: set vm vars for ({{ dist }})
  include_vars: "{{ dist }}/vm.yml"

### Debian
- name: start debian installation
  include: create-vm-debian.yml
  when: template_type == 'debian'

### Ubuntu
- name: start ubuntu installation
  include: create-vm-debian.yml
  when: template_type == 'ubuntu'
