---
- name: 'set vm vars for ({{ virtual_distribution }}/{{ virtual_codename }})'
  include_vars: "{{ virtual_distribution }}/{{ virtual_codename }}/vm.yml"

- name: check if '/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root' exists
  stat:
    path: '/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root'
  register: virtual_disk_root_stat

- name: check if '/etc/libvirt/qemu/{{ virtual_guest_name }}.xml' exists
  stat:
    path: '/etc/libvirt/qemu/{{ virtual_guest_name }}.xml'
  register: virtual_guest_xml_stat

- name: include create disks
  include_tasks: '{{ virtual_hypervisor_type }}/create-disks.yml'
  when: not (virtual_disk_root_stat.stat.exists is defined and virtual_disk_root_stat.stat.exists == True)

- name: include define guest
  include_tasks: '{{ virtual_hypervisor_type }}/define-guest.yml'
  when: not (virtual_guest_xml_stat.stat.exists is defined and virtual_guest_xml_stat.stat.exists == True)
