---
- name: 'set vm vars for ({{ distribution }}/{{ codename }})'
  include_vars: "{{ distribution }}/{{ codename }}/vm.yml"

- name: check if '/dev/{{ vg }}/{{ guest_name }}-root' exists
  stat:
    path: '/dev/{{ vg }}/{{ guest_name }}-root'
  register: guest_lvm_root

- name: check if '/dev/{{ vg }}/{{ guest_name }}-boot' exists
  stat:
    path: '/dev/{{ vg }}/{{ guest_name }}-boot'
  register: guest_lvm_boot

- name: check if '/etc/libvirt/qemu/{{ guest_name }}.xml' exists
  stat:
    path: '/etc/libvirt/qemu/{{ guest_name }}.xml'
  register: guest_xml

- name: include '{{ virtual_hypervisor_type }}/{{ virtual_bootstrap_method }}-{{ virtual_boot_method }}.yml'
  include_tasks: '{{ virtual_hypervisor_type }}/{{ virtual_bootstrap_method }}-{{ virtual_boot_method }}.yml'
  when: not ((guest_lvm_root.stat.exists is defined and guest_lvm_root.stat.exists == True) or (guest_lvm_boot.stat.exists is defined and guest_lvm_boot.stat.exists == True) or (guest_xml.stat.exists is defined and guest_xml.stat.exists == True))
