---
- name: create root lv
  lvol:
    vg: '{{ virtual_disk_vg }}'
    lv: '{{ virtual_guest_name }}-root'
    size: "{{ virtual_disk_size_root }}"

- name: launch vm
  command: |
    virt-install \
    --name={{ virtual_guest_name }} \
    --virt-type=kvm \
    {% if virtual_memory_hotpluggable %}
    --cpu=model=host,cell0.id=0,cell0.cpus={{ virtual_numa_cell_cpus }},cell0.memory={{ virtual_numa_cell_memory }} \
    --memory=memory={{ virtual_memory }},hotplugmemorymax={{ virtual_memory_max }},hotplugmemoryslots={{ virtual_memory_slots }} \
    {% else %}
    --cpu=host \
    --memory={{ virtual_memory }} \
    {% endif %}
    {% if virtual_cpus_hotpluggable %}
    --vcpus=vcpus={{ virtual_cpus }},maxvcpus={{ virtual_cpus_max }} \
    {% else %}
    --vcpus={{ virtual_cpus }} \
    {% endif %}
    {% if virtual_memory_hugepages %}
    --memorybacking=hugepages=yes,size={{ virtual_memory_hugepages_size }},unit={{ virtual_memory_hugepages_unit }} \
    {% endif %}
    {% if virtual_memory_balloon %}
    --memballoon=virtio \
    {% else %}
    --memballoon=none \
    {% endif %}
    --controller=type=scsi,model=virtio-scsi \
    --disk=path=/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-root,bus=scsi,cache=none,address.type=drive,address.controller=0,address.bus=0,address.target=0,address.unit=0,boot_order=1 \
    --os-type=linux \
    --os-variant={{ os_variant }} \
    --console=pty,target_type=serial \
    --location={{ location }} \
    --extra-args='auto=true priority=critical console=ttyS0,115200n8 serial' \
    {% if virtual_mac is defined %}
    --network=bridge={{ virtual_bridge }},model=virtio,target={{ virtual_interface_name }},mac={{ virtual_mac }} \
    {% else %}
    --network=bridge={{ virtual_bridge }},model=virtio,target={{ virtual_interface_name }} \
    {% endif %}
    --nographics \
    --noautoconsole

- name: wait until vm is shut off
  command: /usr/bin/virsh domstate {{ virtual_guest_name }}
  register: result
  until: result.stdout.find("shut off") != -1
  retries: 1000
  delay: 10

- name: start vm
  command: /usr/bin/virsh start {{ virtual_guest_name }}
