- name: set vm vars for ({{ distribution }}/{{ codename }})
  include_vars: "{{ distribution }}/{{ codename }}/vm.yml"

- name: set preseed vars for ({{ distribution }}/{{ codename }})
  include_vars: "{{ distribution }}/{{ codename }}/preseed.yml"

- name: display all environment variables
  debug:
    var: environment
    verbosity: 4

### Debian
- name: start debian installation
  include: install-vm-debian.yml
  when: template_type == 'debian'

### Ubuntu
- name: start ubuntu installation
  include: install-vm-debian.yml
  when: template_type == 'ubuntu'

### Windows
- name: start windows installation
  include: install-vm-windows.yml
  when: template_type == 'windows'
