---
- name: set preseed vars for ({{ virtual_distribution }}/{{ virtual_codename }})
  include_vars: "{{ virtual_distribution }}/{{ virtual_codename }}/preseed.yml"

- name: when virtual boot method is preseed
  when: virtual_boot_method == 'preseed'
  block:

  - name: create preseed base path
    file:
      path: '{{ virtual_preseed_base_path }}'
      state: directory
      owner: root
      group: libvirt-qemu
      mode: '0750'

  - name: create preseed file
    template:
      src: '{{ virtual_preseed_template_type }}/{{ virtual_preseed_filename }}'
      dest: '{{ virtual_preseed_path }}'  # noqa risky-file-permissions

- name: include check
  include_tasks: common/check.yml

- name: wait until guest is shut off
  command:  # noqa no-changed-when
    cmd: "virsh domstate {{ virtual_guest_name }}"
  register: result
  until: result.stdout.find("shut off") != -1
  retries: 1000
  delay: 10

- name: start guest
  command:  # noqa no-changed-when
    cmd: "virsh start {{ virtual_guest_name }}"
