---
- name: create boot lv
  lvol:
    vg: '{{ virtual_disk_vg }}'
    lv: '{{ virtual_guest_name }}-boot'
    size: '{{ virtual_disk_boot_size }}'

- name: dump boot disk from template lv
  command: 'dd if=/dev/{{ virtual_template_vg }}/{{ virtual_template_name }}-{{ virtual_codename }}-boot of=/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-boot bs=1M'
  when: not virtual_template_type == 'file'

- name: dump boot disk from template image
  command: 'dd if={{ virtual_template_path }}/{{ virtual_template_name }}-{{ virtual_codename }}-boot of=/dev/{{ virtual_disk_vg }}/{{ virtual_guest_name }}-boot bs=1M'
  when: virtual_template_type == 'file'
